test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.d753c9a3a0dabbdffc04642e90acf02499f75377.name = "Upgrade from 5.1.36~ynh1"
