#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing nodejs..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir/sources"

#=================================================
# Build
#=================================================
ynh_script_progression "Installing $app..."

pushd "$install_dir/sources"

    ynh_hide_warnings ynh_exec_as_app npm install
    ynh_hide_warnings ynh_exec_as_app BUILD_MODE=dist npm run build
popd

mv "$install_dir/sources/build" "$install_dir/www"
ynh_safe_rm "$install_dir/sources"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated nginx config
ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
